name: Publish Docker image

on:
  push:
    branches:
      - uat
      - prod

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: 'cd java-jerry && mvn clean install -Dmaven.test.skip=true'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}
          username: loopy2023888@gmail.com
          password: lopyDocker2023!

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          images: lopy2023/lopy-java-jerry-svc

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: java-jerry
          push: true
          tags: latest

